### PR TITLE
Fix copyFrom not copying secret type

### LINKED ISSUE #248: ResourceSet copyFrom Secrets type
ResourceSet is not handling the type field for Secrets with copyFrom... it creates them with type `Opaque` which does not work with `secretRef` (for `OCIRepository` it should be `kubernetes.io/dockerconfigjson`)...

As discovered [here](https://github.com/controlplaneio-fluxcd/d2-fleet/issues/7)

### PR DESCRIPTION
**Pull request by matheuscscp**
Fixes #248

### CODE REVIEW

File: internal/controller/resourceset_controller.go [hunk 1]
```diff
@@ -550,6 +550,12 @@ func (r *ResourceSetReconciler) copyResources(ctx context.Context,
 				if err := kubeClient.Get(ctx, sourceName, secret); err != nil {
 					return fmt.Errorf("failed to copy data from Secret/%s: %w", source, err)
 				}
+				if secret.Type == "" {
+					secret.Type = corev1.SecretTypeOpaque
+				}
+				if err := unstructured.SetNestedField(objects[i].Object, string(secret.Type), "type"); err != nil {
+					return fmt.Errorf("failed to copy type from Secret/%s: %w", source, err)
+				}
```
Comment (stefanprodan) [inline internal/controller/resourceset_controller.go:558]: We need to set the type only if it's not present in the ResourceSet https://github.com/controlplaneio-fluxcd/d2-fleet/blob/main/tenants/apps.yaml#L41-L48

So instead of checking the original secret, check the unstructured object first.

Comment (matheuscscp) [reply internal/controller/resourceset_controller.go]: Fixed, thanks!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @matheuscscp 🏅
